name: Infra CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/infra-*.yml'

permissions:
  contents: read
  packages: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: infra

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: infra/package.json
          cache: yarn
          cache-dependency-path: infra/yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile --production=false

      - name: Lint
        run: yarn format:check

      - name: Build
        run: yarn build

  synth:
    name: Synthesize CDK Stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: infra/package.json
          cache: yarn
          cache-dependency-path: infra/yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile --production=false

      - name: Build
        run: yarn build

      # - name: Synthesize CDK Stack
      #   run: yarn cdk synth --context imageVersion=ci-synth-test
      #   env:
      #     CDK_DEFAULT_ACCOUNT: '000000000000'
      #     ENVIRONMENT: production

      - name: Set short SHA
        if: ${{ always() }}
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Mattermost Notification (test)
        if: ${{ always() }}
        uses: adriantaut/action-mattermost-notify@feature/add-color-input
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
          MATTERMOST_CHANNEL: taut-test-notifications
          MATTERMOST_USERNAME: ${{ github.event.repository.name }}-deployer
          COLOR: ${{ job.status }}
          TEXT: |
            ##### Fizzy CDK Deployment
            | | |
            |:--|:--|
            | **Product** | [fizzy](${{ github.server_url }}/${{ github.repository }}) |
            | **Environment** | `production` |
            | **Image Version** | `ci-test` |
            | **Actions URL** | [Deploy](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
            | **Commit** | [`${{ steps.vars.outputs.short_sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) |
            | **Actor** | [${{ github.actor }}](${{ github.server_url }}/${{ github.actor }}) |
